# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 

createCseModuleSpecifications <- function(minExposureSize = 1000) {
  analysis <- list()
  for (name in names(formals(createCseModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  checkmate::assert_file_exists("MetaData.json")
  moduleInfo <- ParallelLogger::loadSettingsFromJson("MetaData.json")
  specifications <- list(module = moduleInfo$Name,
                         version = moduleInfo$Version,
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("ComparatorSelectionExplorerModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
